apiVersion: apps/v1
kind: Deployment
metadata:
  name: c1-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-east1-docker.pkg.dev/advanced-cloud/container1artifact/container1
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: myvolume
              mountPath: /pratik_PV_dir
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: kubernetes-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: container1
spec:
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer