version: '3'
services:
  container1:
    image: pratiksakaria100/container1
    container_name : container1
    ports:
      - "6000:6000"
    volumes:
      - ./:/shared/
    
  container2:
    image: pratiksakaria100/container2
    container_name : container2
    ports:
      - "9001:9001"
    volumes:
      - ./:/shared/
