version: '3'
services:
  container1:
    image: pratiksakaria100/container1:latest
    container_name : container1
    ports:
      - "6000:6000"
    volumes:
      - assignment1_volume:/shared/
      - ./:/shared/
    
  container2:
    image: pratiksakaria100/container2:latest
    container_name : container2
    ports:
      - "9001:9001"
    volumes:
      - assignment1_volume:/shared/
      - ./:/shared/
      
volumes:
    assignment1_volume:
        external: false
        name: assignment1_volume