steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Disk
    entrypoint: "bash"
    args:
      - "-c"
      - |   
        gke-gcloud-auth-plugin --version
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials k8s --zone us-central1-a --project advanced-cloud
        kubectl apply -f disk.yml
        
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/advanced-cloud/container1artifact/container1:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/advanced-cloud/container1artifact/container1:latest",
      ]
      
  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy
    entrypoint: "bash"
    args:
      - "-c"
      - |
        PROJECT=$$(gcloud config get-value core/project)          
        gke-gcloud-auth-plugin --version
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials k8s --zone us-central1-a --project advanced-cloud
        kubectl apply -f container1deployment.yml

images:
  - us-east1-docker.pkg.dev/advanced-cloud/container1artifact/container1:latest
